/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_mob_paysdk_cocos2dx_OnPayListener */

#ifndef _Included_com_mob_paysdk_cocos2dx_OnPayListener
#define _Included_com_mob_paysdk_cocos2dx_OnPayListener
#ifdef __cplusplus
extern "C" {
#endif

JNIEXPORT jboolean JNICALL Java_com_mob_paysdk_cocos2dx_OnPayListener_nativeOnWillPay
  (JNIEnv *, jobject, jlong, jstring, jobject, jobject);

JNIEXPORT void JNICALL Java_com_mob_paysdk_cocos2dx_OnPayListener_nativeOnPayEnd
  (JNIEnv *, jobject, jlong, jobject, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
